CupCarbon v. Klines 7.2
----------------
name:Entrega Semana 3
zoom:1
centerposition_la:4.618873334640968
centerposition_lo:-434.04672503471375
map:1
display_details:true
draw_radio_links:true
draw_sensor_arrows:true
radio_links_color:2
draw_marker_arrows:false
display_rl_distance:false
propagation:true
display_marker_distance:false
display_radio_messages:true
draw_script_file_name:true
display_print_messages:true
display_all_routes:false
